### ISSUE TITLE
 bring the app by its package name

### ISSUE THREAD

**Issue by Djihanegh** [X-SLAYER/bg_launcher#2]
Hello,

Is there a way to make it bring the app from background to foreground by giving its package name, because it sometimes bring the wrong app...

**Comment by X-SLAYER** [comment]
how it bring the wrong app ?

**Comment by Djihanegh** [comment]
For example in my case , if a certain condition is realized , I would bring X app to the foreground, but if I was using another app like 'Z' then my condition is realized, it sometimes brings 'X' to foreground then come back to 'Z' ( bring Z also to foreground ).
How does it work ? And is it possible to make it bring the app by its package name ?

**Comment by X-SLAYER** [comment]
the current package brings the current app with the package name with giving a flag to bring it to the front and when the app has a specific permission

**Comment by Djihanegh** [comment]
What do you mean by the current app ?

**Comment by X-SLAYER** [comment]
when you add this package and call it from your app whether your app is in the background it's gonna bring it to the foreground and front of other apps .
you can run the example
