### ISSUE TITLE
extra

### ISSUE THREAD

**Issue by zouhirdev** [X-SLAYER/bg_launcher#4]
i try to parse my data as a **map** to the extra parameters but it demands it to be a **string?**  how did you do that in the example

![Screenshot (32)](https://github.com/user-attachments/assets/e1d4cf3e-636c-4f24-b9db-b23062018f19)

**Comment by Si11-ibrahim** [comment]
You can use json encode to send it as a string value and you can decode it wherever you want in the app using json decode to extract back to its original form.

**Comment by X-SLAYER** [comment]
a new version has been published please check it out [bg_launcher](https://pub.dev/packages/bg_launcher)
