### ISSUE TITLE
Namespace not specified error

### ISSUE THREAD

**Issue by Si11-ibrahim** [X-SLAYER/bg_launcher#6]
I just added bg_launcher to my app and when I try to run the app I'm getting this error:
![Screenshot 2024-12-29 231147](https://github.com/user-attachments/assets/cc50ad0c-c7aa-4da5-8c01-81e8f0b3790e)
Thank you in advance for any help you can provide.

**Comment by X-SLAYER** [comment]
The Gradle was missing the namespace 
new update has been published please re-check

**Comment by Si11-ibrahim** [comment]
thank you.
